//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_and_data_management.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Has
    {
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int Money_MoneyId { get; set; }
        public int Wallet_WalletId { get; set; }
        public int Bill_BillId { get; set; }
        public decimal Has_ID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
