//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_and_data_management.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money
    {
        public int MoneyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal Has_Has_ID { get; set; }
        public string Name { get; set; }
    }
}
