//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MoneyDBEntities : DbContext
    {
        public MoneyDBEntities()
            : base("name=MoneyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<Regular> Regulars { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Valute> Valutes { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<Workstation> Workstations { get; set; }
    
        public virtual ObjectResult<sp_GetFilesForWorkstation_Result> sp_GetFilesForWorkstation(Nullable<int> workstationId)
        {
            var workstationIdParameter = workstationId.HasValue ?
                new ObjectParameter("WorkstationId", workstationId) :
                new ObjectParameter("WorkstationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFilesForWorkstation_Result>("sp_GetFilesForWorkstation", workstationIdParameter);
        }
    }
}
